// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTOAxy72AH2SMLOBoaI4Lz4mm9hOcyv5s',
    appId: '1:93516631475:web:1b3a79d0837e6e5d180fc6',
    messagingSenderId: '93516631475',
    projectId: 'cadi-prod',
    authDomain: 'cadi-prod.firebaseapp.com',
    storageBucket: 'cadi-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHmlDniSkkBU25rJjNZe3VWY7LmLw8shM',
    appId: '1:93516631475:android:1818bbd86a10d8df180fc6',
    messagingSenderId: '93516631475',
    projectId: 'cadi-prod',
    storageBucket: 'cadi-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6VyOM3wx0Yw8ov4XgV7Jn2T1Ev_4uy0g',
    appId: '1:93516631475:ios:f855a3c285109713180fc6',
    messagingSenderId: '93516631475',
    projectId: 'cadi-prod',
    storageBucket: 'cadi-prod.firebasestorage.app',
    iosBundleId: 'com.example.cadiAdminWeb',
  );

}